### ISSUE TITLE
Main function returns error

### ISSUE THREAD

**Issue by jibnew** [danielrademacher/BruhatDecomposition#7]
Many thanks for your work! Your code is impressively quick!

I managed to use the commands `BruhatDecompositionSL`, etc. successfully, as described in the manual.
However when I try, for example, `BruhatDecomposition(PseudoRandom(SL(3,4)))`, I get this:
```
Error, the dimension <d> must be even at /usr/src/gap-master/grp/classic.gi:27 called from
SymplecticGroupCons( IsMatrixGroup, arg[1], arg[2] ) at /usr/src/gap-master/grp/classic.gd:609 called from
Sp( d, q ) at /usr/src/gap-master/pkg/BruhatDecomposition-0.1/gap/BruhatDecomposition.gi:18 called from
<function "BruhatDecomposition">( <arguments> )
 called from read-eval loop at *stdin*:16
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```
What am I doing wrong?
In case the problem is with my GAP distribution, here is the header I get at the beginning:
```
 ┌───────┐   GAP 4.12dev built on 2020-04-23 19:33:32+0400
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-cygwin-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loaded workspace: /cygdrive/d/prog/gap/Sasha/spin15
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, AutPGrp 1.10.2, CaratInterface 2.3.3, CoReLG 1.54, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.3.1, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.3, GRAPE 4.8.3, IRREDSOL 1.4.1, LAGUNA 3.9.3, Polenta 1.3.9, Polycyclic 2.15.1, PrimGrp 3.4.0, QuaGroup 1.8.2, RadiRoot 2.8, ResClasses 4.7.2, singular 2020.12.18, SLA 1.5.3, SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 2.0.6, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```
As you see, I am running GAP through cygwin, on Windows 11, my `uname --all` returns
```
CYGWIN_NT-10.0-22621 DESKTOP-M4AP3T8 3.3.6-341.x86_64 2022-09-05 11:15 UTC x86_64 Cygwin
```

**Comment by danielrademacher** [comment]
Hi, 

thanks a lot for using my package and for discovering this error. I have updated the main function such that this shouldn't be a problem anymore. The function ```BruhatDecomposition(g)``` tries to compute in which classical group ```g``` is contained. Since some of the classical groups of small rank are isomorphic to each other, the function could give the Bruhat decomposition in an other classical group. I also added a small statement for this.

I hope this solves the error. If it still occurs or if you discover something else, please feel free to open another issue!

Best wishes
Daniel
